In [18]:
##importing the csv into the notebook
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
#import seaborn as sb
#import matplotlib.pyplot as plt # we only need pyplot
#!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\yong jian rong\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\yong jian rong\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

Error processing line 1 of C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\Yong Jian Rong\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored

Requirement already satisfied: openpyxl in c:\users\yong jian rong\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\yong jian rong\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

Error processing line 1 of C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\Yong Jian Rong\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored

In [19]:
llist = ["page"+str(x) for x in range(1,16)]
llist.insert(0, 'combined_dist stable')
print(llist)
combined = pd.read_excel("./combined_dist_stable.xlsx", sheet_name=llist, engine='openpyxl') #import fresh data

['combined_dist stable', 'page1', 'page2', 'page3', 'page4', 'page5', 'page6', 'page7', 'page8', 'page9', 'page10', 'page11', 'page12', 'page13', 'page14', 'page15']

In [6]:
final = pd.DataFrame()
for item in llist:
    temp = combined.get(item)
    final = pd.concat([final,temp])

In [7]:
final

,Unnamed: 0,blk_no,street,max_floor_lvl,year_completed,residential,commercial,market_hawker,miscellaneous,multistorey_carpark,...,stop_id,line,no,lng_mrt,lat_mrt,mahattan_distance,mrt_cbd_dist,mrt_cbd_time,hdb_cbd_distance,hdb_cbd_time
0,0,1,BEACH RD,16,1970,Y,Y,N,N,N,...,CC3,CC,48,103.855504,1.293322,1612.353588,2025.9,3.016667,2283.5,3.668333
1,1,1,BEACH RD,16,1970,Y,Y,N,N,N,...,EW13 / NS25,EW,36,103.852586,1.292936,1245.657873,2159.7,3.623333,2283.5,3.668333
2,4,3,BEACH RD,16,1970,Y,Y,N,N,N,...,CC3,CC,48,103.855504,1.293322,1612.353588,2025.9,3.016667,2888.2,4.773333
3,5,3,BEACH RD,16,1970,Y,Y,N,N,N,...,EW13 / NS25,EW,36,103.852586,1.292936,1245.657873,2159.7,3.623333,2888.2,4.773333
4,8,1,BEDOK STH AVE 1,14,1975,Y,N,N,Y,N,...,EW4,EW,143,103.946347,1.327187,15454.933480,15580.1,18.738333,13450.9,16.058333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,578,2,JOO CHIAT RD,5,1985,N,Y,N,N,Y,...,EW7,EW,49,103.903252,1.319779,9849.191172,9047.3,12.905000,7955.5,11.115000
15,579,2,JOO CHIAT RD,5,1985,N,Y,N,N,Y,...,EW8,EW,104,103.893060,1.318112,8532.845502,7805.2,10.488333,7955.5,11.115000
16,580,2,JOO CHIAT RD,5,1985,N,Y,N,N,Y,...,CC9,CC,104,103.892179,1.317430,8359.306548,7658.2,10.485000,7955.5,11.115000
17,584,2A,EUNOS CRES,2,1981,Y,Y,N,N,N,...,EW7,EW,49,103.903252,1.319779,9849.191172,9047.3,12.905000,9046.4,12.900000
18,585,2A,EUNOS CRES,2,1981,Y,Y,N,N,N,...,EW8,EW,104,103.893060,1.318112,8532.845502,7805.2,10.488333,9046.4,12.900000

In [9]:
resale_prc = pd.read_csv('./resale-flat-prices-based-on-registration-date-from-jan-2017-onwards.csv')

In [10]:
resale_prc

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
80369,2020-09,YISHUN,5 ROOM,716,YISHUN ST 71,07 TO 09,131.0,Improved,1987,66 years 03 months,440000.0
80370,2020-09,YISHUN,5 ROOM,760,YISHUN ST 72,07 TO 09,122.0,Improved,1987,65 years 06 months,458000.0
80371,2020-09,YISHUN,5 ROOM,835,YISHUN ST 81,04 TO 06,122.0,Improved,1987,66 years 04 months,490000.0
80372,2020-09,YISHUN,EXECUTIVE,791,YISHUN AVE 2,04 TO 06,146.0,Maisonette,1987,66 years 03 months,558000.0
80373,2020-09,YISHUN,EXECUTIVE,387,YISHUN RING RD,04 TO 06,146.0,Maisonette,1988,66 years 09 months,555000.0

In [11]:
resale_prc = resale_prc.rename(columns = {'street_name':'street', 'block':'blk_no'})
resale_prc

,month,town,flat_type,blk_no,street,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0
...,...,...,...,...,...,...,...,...,...,...,...
80369,2020-09,YISHUN,5 ROOM,716,YISHUN ST 71,07 TO 09,131.0,Improved,1987,66 years 03 months,440000.0
80370,2020-09,YISHUN,5 ROOM,760,YISHUN ST 72,07 TO 09,122.0,Improved,1987,65 years 06 months,458000.0
80371,2020-09,YISHUN,5 ROOM,835,YISHUN ST 81,04 TO 06,122.0,Improved,1987,66 years 04 months,490000.0
80372,2020-09,YISHUN,EXECUTIVE,791,YISHUN AVE 2,04 TO 06,146.0,Maisonette,1987,66 years 03 months,558000.0
80373,2020-09,YISHUN,EXECUTIVE,387,YISHUN RING RD,04 TO 06,146.0,Maisonette,1988,66 years 09 months,555000.0

In [23]:
# Merge resale_prc DF with 'final' DF.
combined = resale_prc.merge(final, on=['street', 'blk_no'])

In [24]:
combined

,month,town,flat_type,blk_no,street,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,...,stop_id,line,no,lng_mrt,lat_mrt,mahattan_distance,mrt_cbd_dist,mrt_cbd_time,hdb_cbd_distance,hdb_cbd_time
0,2017-01,ANG MO KIO,3 ROOM,571,ANG MO KIO AVE 3,01 TO 03,67.0,New Generation,1979,61 years 04 months,...,NS16,NS,2,103.849933,1.369347,9736.287744,13146.7,13.406667,12838.5,13.383333
1,2017-02,ANG MO KIO,3 ROOM,571,ANG MO KIO AVE 3,04 TO 06,67.0,New Generation,1979,61 years 03 months,...,NS16,NS,2,103.849933,1.369347,9736.287744,13146.7,13.406667,12838.5,13.383333
2,2017-05,ANG MO KIO,3 ROOM,571,ANG MO KIO AVE 3,10 TO 12,67.0,New Generation,1979,61 years,...,NS16,NS,2,103.849933,1.369347,9736.287744,13146.7,13.406667,12838.5,13.383333
3,2017-08,ANG MO KIO,3 ROOM,571,ANG MO KIO AVE 3,04 TO 06,82.0,New Generation,1979,60 years 09 months,...,NS16,NS,2,103.849933,1.369347,9736.287744,13146.7,13.406667,12838.5,13.383333
4,2017-09,ANG MO KIO,3 ROOM,571,ANG MO KIO AVE 3,07 TO 09,67.0,New Generation,1979,60 years 08 months,...,NS16,NS,2,103.849933,1.369347,9736.287744,13146.7,13.406667,12838.5,13.383333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89618,2020-09,SENGKANG,5 ROOM,164A,RIVERVALE CRES,07 TO 09,113.0,Improved,2017,95 years 08 months,...,SE4,SE,71,103.902174,1.383979,16855.672120,15973.0,18.775000,16496.2,19.298333
89619,2020-09,SENGKANG,5 ROOM,164A,RIVERVALE CRES,07 TO 09,113.0,Improved,2017,95 years 08 months,...,SE3,SE,3,103.905439,1.388093,17674.730240,16402.9,19.116667,16496.2,19.298333
89620,2020-09,SENGKANG,5 ROOM,164A,RIVERVALE CRES,07 TO 09,113.0,Improved,2017,95 years 08 months,...,SE2,SE,121,103.905974,1.391468,18108.772770,16877.7,19.843333,16496.2,19.298333
89621,2020-09,TOA PAYOH,3 ROOM,186,TOA PAYOH CTRL,04 TO 06,64.0,Improved,1972,50 years 10 months,...,NS19,NS,152,103.847502,1.332629,5930.417757,9270.9,12.716667,9911.0,13.973333
89622,2020-09,TOA PAYOH,EXECUTIVE,124,POTONG PASIR AVE 1,01 TO 03,151.0,Maisonette,1984,62 years 06 months,...,NE10,NE,109,103.869056,1.331380,7341.009975,8560.7,10.060000,8927.5,10.720000

In [48]:
import requests
import json# call the OSMR API

i=1


def router(row):
    lon_1, lat_1, lon_2, lat_2 = row['lng_hdb'], row['lat_hdb'], row['lng_mrt'], row['lat_mrt']
    
    global i
    r = requests.get(f"http://router.project-osrm.org/route/v1/car/{lon_1},{lat_1};{lon_2},{lat_2}?overview=false""")# then you load the response using the json libray
    # by default you get only one alternative so you access 0-th element of the `routes`
    
    routes = json.loads(r.content)
    # print(routes)
    route_1 = routes.get("routes")[0]
    # print(f"Overall, the route data is:\n{route_1}\n")
    seconds = route_1['legs'][0]['duration']
    #print(f"Duration: {seconds}sec ({seconds/60:.2f} min )")
    print("row", i)
    print(route_1['legs'][0]['distance'])
    i += 1

    return float(route_1['legs'][0]['distance']), float(seconds/60.0)
    
def walker(row):
    lon_1, lat_1, lon_2, lat_2 = row['lng_hdb'], row['lat_hdb'], row['lng_mrt'], row['lat_mrt']
    
    global i
    r = requests.get(f"http://router.project-osrm.org/route/v1/foot/{lon_1},{lat_1};{lon_2},{lat_2}?overview=false""")# then you load the response using the json libray
    # by default you get only one alternative so you access 0-th element of the `routes`
    
    routes = json.loads(r.content)
    # print(routes)
    route_1 = routes.get("routes")[0]
    # print(f"Overall, the route data is:\n{route_1}\n")
    seconds = route_1['legs'][0]['duration']
    #print(f"Duration: {seconds}sec ({seconds/60:.2f} min )")
    print("row", i)
    print(route_1['legs'][0]['distance'])
    i += 1

    return float(route_1['legs'][0]['distance']), float(seconds/60.0)

In [46]:
#import os 
#combined.to_csv('./combined_resale.csv') 
shortened = combined.drop_duplicates(subset=['postal'])
shortened.shape
geylangb = shortened[shortened['name']=='GEYLANG BAHRU MRT STATION']

In [30]:
# Running by sections - Not used for HDB to MRT, only 4000 values.

section = {} # Create a dict, split into sections
i=0
jump=10
## Trial debug
while i < 50:
#while i < combined.shape[0]+jump:
    section[int(i/jump)]=combined.iloc[i:i+jump-1]
    print(combined.iloc[i:i+jump-1]['postal'])
    i+=jump

0    560571
1    560571
2    560571
3    560571
4    560571
5    560571
6    560571
7    560571
8    560571
Name: postal, dtype: object
10    560571
11    560571
12    560571
13    560571
14    560571
15    560571
16    560571
17    560534
18    560534
Name: postal, dtype: object
20    560534
21    560534
22    560534
23    560534
24    560534
25    560534
26    560534
27    560534
28    560534
Name: postal, dtype: object
30    560536
31    560536
32    560536
33    560536
34    560536
35    560536
36    560536
37    560536
38    560536
Name: postal, dtype: object
40    560536
41    560536
42    560536
43    560536
44    560570
45    560570
46    560570
47    560570
48    560570
Name: postal, dtype: object

In [28]:
print(section.keys())

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90])

In [33]:
i=0
for key, part in section.items():
    print(f"Current section:{key*jump} to {(key+1)*jump-1}")
    print(f"Total no. of sections: {len(section)}\n")

    #print(part)
    part[['hdbtomrt_distance', 'hdbtomrt_time']]  = part.apply(router, axis=1, result_type='expand')
    writer = pd.ExcelWriter('hdb_to_mrt.xlsx', engine = 'openpyxl',mode='a',if_sheet_exists='replace')
    part.to_excel(writer, sheet_name = f'page{key}')
    writer.close()

Current section:0 to 9
Total no. of sections: 5

row 0
1979.7
row 1
1979.7
row 2
1979.7
row 3
1979.7
row 4
1979.7
row 5
1979.7
row 6
1979.7
row 7
1979.7
row 8
1979.7

C:\Users\Yong Jian Rong\AppData\Local\Temp\ipykernel_41736\356773607.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  part[['hdbtomrt_distance', 'hdbtomrt_time']]  = part.apply(router, axis=1, result_type='expand')

Current section:10 to 19
Total no. of sections: 5

row 9
1979.7
row 10
1979.7
row 11
1979.7
row 12
1979.7
row 13
1979.7
row 14
1979.7
row 15
1979.7
row 16
2023.2
row 17
2023.2
Current section:20 to 29
Total no. of sections: 5

row 18
2023.2
row 19
2023.2
row 20
2023.2
row 21
2023.2
row 22
2023.2
row 23
2023.2
row 24
2023.2
row 25
2023.2
row 26
2023.2
Current section:30 to 39
Total no. of sections: 5

row 27
1678.9
row 28
1678.9
row 29
1678.9
row 30
1678.9
row 31
1678.9
row 32
1678.9
row 33
1678.9
row 34
1678.9
row 35
1678.9
Current section:40 to 49
Total no. of sections: 5

row 36
1678.9
row 37
1678.9
row 38
1678.9
row 39
1678.9
row 40
1608.5
row 41
1608.5
row 42
1608.5
row 43
1608.5
row 44
1608.5

In [49]:
geylangb[['hdbtomrt_distance', 'hdbtomrt_time']]  = geylangb.apply(walker, axis=1, result_type='expand')
writer = pd.ExcelWriter('hdb_to_mrt - gb.xlsx', engine = 'openpyxl',mode='a',if_sheet_exists='replace')
geylangb.to_excel(writer, sheet_name = 'gb')
writer.close()

row 1
6724.8
row 2
7470.6
row 3
6818.3
row 4
7113.7
row 5
7573.8
row 6
6645.4
row 7
6671.1
row 8
7468
row 9
6753.6
row 10
6770.5
row 11
6600.5

KeyboardInterrupt: