In [9]:
##importing the csv into the notebook
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
#from sklearn.cluster import KMeans
#from sklearn.cluster import kmeans_plusplus
#from sklearn.neighbors import NearestNeighbors
#from sklearn.cluster import DBSCAN
#from sklearn.preprocessing import MinMaxScaler
#from sklearn.preprocessing import StandardScaler
#import time
#from sklearn.metrics import silhouette_samples, silhouette_score
#from mpl_toolkits import mplot3d 
#from mpl_toolkits.mplot3d import Axes3D
sb.set() # set the default Seaborn style for graphics
pd.options.mode.chained_assignment = None
#scaler = MinMaxScaler() #you might need to change this according to the data set we have

In [10]:
busline = pd.read_csv("./bus_line.csv", index_col = [0]) #import fresh data  
#busline[['distance']] = scaler.fit_transform(busline[['distance']])
busline.head()

,line,operator,direction,sequence,stop_id,distance,WD_FirstBus,WD_LastBus,SAT_FirstBus,SAT_LastBus,SUN_FirstBus,SUN_LastBus
0,10,SBST,1,1,75009,0.0,500,2300,500,2300,500,2300
1,10,SBST,1,2,76059,0.6,502,2302,502,2302,502,2302
2,10,SBST,1,3,76069,1.1,504,2304,504,2304,503,2304
3,10,SBST,1,4,96289,2.3,508,2308,508,2309,507,2308
4,10,SBST,1,5,96109,2.7,509,2310,509,2311,508,2309

In [11]:
hdb = pd.read_csv("./hdb.csv", index_col = [0]) #import fresh data  
#busline[['distance']] = scaler.fit_transform(busline[['distance']])
hdb.head()

,blk_no,street,max_floor_lvl,year_completed,residential,commercial,market_hawker,miscellaneous,multistorey_carpark,precinct_pavilion,...,building,addr,postal,SUBZONE_NO,SUBZONE_N,SUBZONE_C,PLN_AREA_N,PLN_AREA_C,REGION_N,REGION_C
0,1,BEACH RD,16,1970,Y,Y,N,N,N,N,...,RAFFLES HOTEL,1 BEACH ROAD RAFFLES HOTEL SINGAPORE 189673,189673,2.0,CITY HALL,DTSZ02,DOWNTOWN CORE,DT,CENTRAL REGION,CR
1,1,BEDOK STH AVE 1,14,1975,Y,N,N,Y,N,N,...,NIL,1 BEDOK SOUTH AVENUE 1 SINGAPORE 460001,460001,6.0,BEDOK SOUTH,BDSZ06,BEDOK,BD,EAST REGION,ER
2,1,CANTONMENT RD,2,2010,N,Y,N,N,N,N,...,PINNACLE @ DUXTON,1 CANTONMENT ROAD PINNACLE @ DUXTON SINGAPORE ...,080001,3.0,CHINATOWN,OTSZ03,OUTRAM,OT,CENTRAL REGION,CR
3,1,CHAI CHEE RD,15,1982,Y,N,N,N,N,N,...,PING YI GARDENS,1 CHAI CHEE ROAD PING YI GARDENS SINGAPORE 461001,461001,3.0,KEMBANGAN,BDSZ03,BEDOK,BD,EAST REGION,ER
4,1,CHANGI VILLAGE RD,4,1975,Y,Y,N,N,N,N,...,OCBC CHANGI VILLAGE ROAD - 7 ELEVEN,1 CHANGI VILLAGE ROAD OCBC CHANGI VILLAGE ROAD...,500001,1.0,CHANGI POINT,CHSZ01,CHANGI,CH,EAST REGION,ER

In [12]:
mrt = pd.read_csv("./mrt.csv", index_col = [0]) #import fresh data  
#busline[['distance']] = scaler.fit_transform(busline[['distance']])
mrt.head()

,name,stop_id,line,no,lng,lat,SUBZONE_NO,SUBZONE_N,SUBZONE_C,PLN_AREA_N,PLN_AREA_C,REGION_N,REGION_C
0,EUNOS MRT STATION,EW7,EW,49,103.903252,1.319779,5,GEYLANG EAST,GLSZ05,GEYLANG,GL,CENTRAL REGION,CR
1,CHINESE GARDEN MRT STATION,EW25,EW,33,103.732597,1.342353,4,LAKESIDE (LEISURE),JESZ04,JURONG EAST,JE,WEST REGION,WR
2,KHATIB MRT STATION,NS14,NS,75,103.832980,1.417383,8,KHATIB,YSSZ08,YISHUN,YS,NORTH REGION,NR
3,KRANJI MRT STATION,NS7,NS,78,103.762165,1.425178,2,TURF CLUB,SKSZ02,SUNGEI KADUT,SK,NORTH REGION,NR
4,REDHILL MRT STATION,EW18,EW,117,103.816817,1.289563,3,REDHILL,BMSZ03,BUKIT MERAH,BM,CENTRAL REGION,CR

In [19]:
combined = hdb.merge(mrt, on=['SUBZONE_NO', 'SUBZONE_C', 'SUBZONE_C', 'PLN_AREA_N', 'PLN_AREA_C', 'REGION_N', 'REGION_C'])

In [20]:
combined

,blk_no,street,max_floor_lvl,year_completed,residential,commercial,market_hawker,miscellaneous,multistorey_carpark,precinct_pavilion,...,PLN_AREA_C,REGION_N,REGION_C,name,stop_id,line,no,lng_y,lat_y,SUBZONE_N_y
0,1,BEACH RD,16,1970,Y,Y,N,N,N,N,...,DT,CENTRAL REGION,CR,ESPLANADE MRT STATION,CC3,CC,48,103.855504,1.293322,CITY HALL
1,1,BEACH RD,16,1970,Y,Y,N,N,N,N,...,DT,CENTRAL REGION,CR,CITY HALL MRT STATION,EW13 / NS25,EW,36,103.852586,1.292936,CITY HALL
2,1,BEACH RD,16,1970,Y,Y,N,N,N,N,...,DT,CENTRAL REGION,CR,CITY HALL MRT STATION,EW13 / NS25,NS,36,103.852586,1.292936,CITY HALL
3,1,BEACH RD,16,1970,Y,Y,N,N,N,N,...,DT,CENTRAL REGION,CR,CITY HALL MRT STATION,EW13 / NS25,CG,36,103.852586,1.292936,CITY HALL
4,3,BEACH RD,16,1970,Y,Y,N,N,N,N,...,DT,CENTRAL REGION,CR,ESPLANADE MRT STATION,CC3,CC,48,103.855504,1.293322,CITY HALL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15713,850,HOUGANG CTRL,16,1995,Y,N,N,N,N,N,...,HG,NORTH-EAST REGION,NER,HOUGANG MRT STATION,NE14,NE,63,103.892381,1.371292,HOUGANG CENTRAL
15714,850A,HOUGANG CTRL,5,1995,N,N,N,N,Y,N,...,HG,NORTH-EAST REGION,NER,HOUGANG MRT STATION,NE14,NE,63,103.892381,1.371292,HOUGANG CENTRAL
15715,851,HOUGANG CTRL,16,1995,Y,N,N,N,N,N,...,HG,NORTH-EAST REGION,NER,HOUGANG MRT STATION,NE14,NE,63,103.892381,1.371292,HOUGANG CENTRAL
15716,852,HOUGANG CTRL,16,1995,Y,N,N,N,N,N,...,HG,NORTH-EAST REGION,NER,HOUGANG MRT STATION,NE14,NE,63,103.892381,1.371292,HOUGANG CENTRAL
15717,853,HOUGANG CTRL,16,1995,Y,N,N,N,N,N,...,HG,NORTH-EAST REGION,NER,HOUGANG MRT STATION,NE14,NE,63,103.892381,1.371292,HOUGANG CENTRAL

In [14]:
#5b3ce3597851110001cf6248efe1fcd54b844858b7c91fc9d6e5fdb3
#!pip install pandas
!pip install openrouteservice folium

import openrouteservice
import json
client = openrouteservice.Client(key='5b3ce3597851110001cf6248efe1fcd54b844858b7c91fc9d6e5fdb3')

#set location coordinates in longitude,latitude order
coords = ((103.83425, 1.28937),(103.85146, 1.28412))
#call API
res = client.directions(coords)
#test our response
test = json.loads(res,indent=4, sort_keys=True)
print(res["routes"][0]["segments"][0]['duration'])

Requirement already satisfied: openrouteservice in c:\users\yong jian rong\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: folium in c:\users\yong jian rong\anaconda3\lib\site-packages (0.12.1.post1)
Requirement already satisfied: requests>=2.0 in c:\users\yong jian rong\anaconda3\lib\site-packages (from openrouteservice) (2.27.1)
Requirement already satisfied: jinja2>=2.9 in c:\users\yong jian rong\anaconda3\lib\site-packages (from folium) (2.11.3)
Requirement already satisfied: numpy in c:\users\yong jian rong\anaconda3\lib\site-packages (from folium) (1.22.3)
Requirement already satisfied: branca>=0.3.0 in c:\users\yong jian rong\anaconda3\lib\site-packages (from folium) (0.5.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\yong jian rong\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (2.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\yong jian rong\anaconda3\lib\site-packages (from requests>=2.0->openrouteservice) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\yong jian rong\anaconda3\lib\site-packages (from requests>=2.0->openrouteservice) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yong jian rong\anaconda3\lib\site-packages (from requests>=2.0->openrouteservice) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yong jian rong\anaconda3\lib\site-packages (from requests>=2.0->openrouteservice) (3.3)

Error processing line 1 of C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\Yong Jian Rong\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored

TypeError: the JSON object must be str, bytes or bytearray, not dict

In [ ]:
coords = ((103.83425, 1.28937),(103.85146, 1.28412))
combined['json'] = combined.apply(lambda row: client.directions(coords), axis=1)

C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 1st time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 2nd time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 3rd time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 4th time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 5th time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 6th time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 1st time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 2nd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 3rd time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 4th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 5th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:211: UserWarning: Rate limit exceeded. Retrying for the 6th time.
  warnings.warn('Rate limit exceeded. Retrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 7th time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,
C:\Users\Yong Jian Rong\anaconda3\lib\site-packages\openrouteservice\client.py:195: UserWarning: Server down.
Retrying for the 8th time.
  warnings.warn('Server down.\nRetrying for the {0}{1} time.'.format(retry_counter + 1,

In [ ]:
combined

In [16]:
# https://kanoki.org/2019/12/27/how-to-calculate-distance-in-python-and-pandas-using-scipy-spatial-and-distance-functions/

def manhattan(lon1, lat1, lon2, lat2):

    lon1, lat1, lon2, lat2 = lon1, lat1, lon2, lat2

    newlon = (lon2 - lon1)*111000
    newlat = (lat2 - lat1)*111000
    
    distance = abs(newlon) + abs(newlat)

    
    return distance

In [17]:
#lat and long from raffles place mrt station 
combined['distance'] = combined.apply(lambda row: manhattan(row.lng_y, row.lat_y, 103.8513,1.2830 ), axis=1)

NameError: name 'combined' is not defined

In [15]:
combined[combined['name']=='JURONG EAST MRT STATION']

NameError: name 'combined' is not defined